#!/usr/bin/env bash
set -eu
set -o pipefail

mydumper -B ${ORIGIN_DB_NAME} -o /dumpdir -c -C -e -h ${ORIGIN_DB_HOST} -P ${ORIGIN_DB_PORT} -p ${ORIGIN_DB_PASS} -u ${ORIGIN_DB_USER} --tz-utc
myloader -d /dumpdir -o -B ${DEST_DB_NAME} -s ${ORIGIN_DB_NAME} -h ${DEST_DB_HOST} -P ${DEST_DB_PORT} -p ${DEST_DB_PASS} -u ${DEST_DB_USER} -C
